#!/usr/bin/env node
// ============================================================================
// GTCX meta-workspace setup
//
// Generates the root pnpm-workspace.yaml at the GTCX-ECOSYSTEM workspace root
// so member repos install as one workspace (cross-repo `workspace:*` deps).
//
// Members are declared in machine/meta-workspace/members.json with optional
// vertical-qualified `path` (post-2026-07-05 reorg).
// ============================================================================

import { readFileSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ECO_OS = join(HERE, '../../..'); // .../ecosystem-os
const MEMBERS_PATH = join(ECO_OS, 'machine/meta-workspace/members.json');

const args = new Set(process.argv.slice(2));
const includeCandidates = args.has('--include-candidates');

function fail(msg) {
  console.error(`meta-workspace: ${msg}`);
  process.exit(1);
}

/** Walk up from ecosystem-os to gtcx-ecosystem workspace root (vertical layout). */
function findMetaWorkspaceRoot(fromDir) {
  const env = process.env.GTCX_ECOSYSTEM_ROOT;
  if (
    env &&
    existsSync(env) &&
    existsSync(join(env, 'gtcx.infrastructure')) &&
    existsSync(join(env, 'gtcx.ecosystem'))
  ) {
    return env;
  }

  let dir = fromDir;
  for (let i = 0; i < 6; i++) {
    if (
      existsSync(join(dir, 'gtcx.infrastructure')) &&
      existsSync(join(dir, 'gtcx.ecosystem'))
    ) {
      return dir;
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  fail(`could not find gtcx-ecosystem root from ${fromDir}`);
}

const PARENT = findMetaWorkspaceRoot(ECO_OS);
const ROOT_WS = join(PARENT, 'pnpm-workspace.yaml');

const spec = JSON.parse(readFileSync(MEMBERS_PATH, 'utf8'));
const members = (spec.members ?? []).filter(
  (m) => m.status === 'verified' || (includeCandidates && m.status === 'candidate'),
);

function memberRelPath(m) {
  return m.path ?? m.repo;
}

function memberGlobs(memberPath) {
  const wsPath = join(PARENT, memberPath, 'pnpm-workspace.yaml');
  if (!existsSync(wsPath)) fail(`member ${memberPath} has no pnpm-workspace.yaml`);
  const lines = readFileSync(wsPath, 'utf8').split('\n');
  const out = [];
  for (const line of lines) {
    const m = line.match(/^\s*-\s*'([^']+)'\s*$/) || line.match(/^\s*-\s*"([^"]+)"\s*$/);
    if (!m) continue;
    const g = m[1].trim();
    if (g === '.') continue;
    out.push(`${memberPath}/${g}`);
  }
  return out;
}

const globs = [];
const summary = [];
for (const m of members) {
  const rel = memberRelPath(m);
  const repoRoot = join(PARENT, rel);
  if (!existsSync(repoRoot)) fail(`member repo not present: ${m.repo} (expected at ${repoRoot})`);
  const g = memberGlobs(rel);
  globs.push(...g);
  summary.push(`${m.repo} → ${rel} (${m.status}): ${g.length} package globs`);
}
globs.sort();

const header = [
  '# GENERATED by ecosystem-os/platform/scripts/meta-workspace/setup.mjs — do not hand-edit.',
  '# GTCX meta-workspace: member repos install as one workspace so cross-repo',
  '# workspace:* deps resolve by membership. Regenerate: pnpm --dir gtcx.ecosystem/ecosystem-os meta:workspace:write',
  `# Members: ${members.map((m) => `${m.repo}@${memberRelPath(m)}`).join(', ')}`,
  '',
  'packages:',
];
const content = header.concat(globs.map((g) => `  - '${g}'`)).join('\n') + '\n';

if (args.has('--remove')) {
  if (existsSync(ROOT_WS)) {
    rmSync(ROOT_WS);
    console.log(`meta-workspace: removed ${ROOT_WS}`);
  } else {
    console.log('meta-workspace: no root workspace to remove');
  }
  process.exit(0);
}

console.log(`meta-workspace root: ${PARENT}`);
console.log(`meta-workspace: ${members.length} members, ${globs.length} packages`);
summary.forEach((s) => console.log(`  - ${s}`));

if (args.has('--check')) {
  if (!existsSync(ROOT_WS)) fail('root workspace missing — run with --write');
  const current = readFileSync(ROOT_WS, 'utf8');
  if (current.trim() !== content.trim()) fail('root workspace is STALE — run with --write');
  console.log('meta-workspace: root workspace up to date ✓');
  process.exit(0);
}

if (args.has('--write')) {
  writeFileSync(ROOT_WS, content);
  console.log(`meta-workspace: wrote ${ROOT_WS} (${globs.length} packages)`);
  console.log('  next: run `pnpm install` from the gtcx-ecosystem parent for meta mode.');
  process.exit(0);
}

console.log('\n--- DRY (no write). Would write to:', ROOT_WS, '---');
console.log(content.split('\n').slice(0, 12).join('\n'));
console.log(`  ... (${globs.length} package globs total)`);
console.log('\nRun with --write to materialize, --check for CI drift, --remove to tear down.');
